// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-_T7oz4Eb-v_0QQ6qgtGcs8MU2L_NZQ',
    appId: '1:613874008104:web:954eea7bf197f02fa7751d',
    messagingSenderId: '613874008104',
    projectId: 'testflutter-8c9a1',
    authDomain: 'testflutter-8c9a1.firebaseapp.com',
    databaseURL: 'https://testflutter-8c9a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testflutter-8c9a1.appspot.com',
    measurementId: 'G-2CGD4JGCCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5onybHGdEgF3549J5jbSWOa_2G0j3bU',
    appId: '1:613874008104:android:efc8088b64466881a7751d',
    messagingSenderId: '613874008104',
    projectId: 'testflutter-8c9a1',
    databaseURL: 'https://testflutter-8c9a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testflutter-8c9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9WLdR6loWmn7AGOzSRrfZnp7liuBuQg',
    appId: '1:613874008104:ios:e81dab41850344fea7751d',
    messagingSenderId: '613874008104',
    projectId: 'testflutter-8c9a1',
    databaseURL: 'https://testflutter-8c9a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testflutter-8c9a1.appspot.com',
    iosClientId: '613874008104-ggceqbd7lsf1vkejb2bourrjfrglj99r.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD9WLdR6loWmn7AGOzSRrfZnp7liuBuQg',
    appId: '1:613874008104:ios:e81dab41850344fea7751d',
    messagingSenderId: '613874008104',
    projectId: 'testflutter-8c9a1',
    databaseURL: 'https://testflutter-8c9a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testflutter-8c9a1.appspot.com',
    iosClientId: '613874008104-ggceqbd7lsf1vkejb2bourrjfrglj99r.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
