name: apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_ui_auth: ^1.3.0
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.5.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  responsive_grid: ^2.2.0
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  firebase_messaging: ^14.6.1
  uuid: ^3.0.7
  date_time_picker: ^2.1.0
  flutter_datetime_picker: ^1.5.1


english_words: ^4.0.0
provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


